Feature/cakephp challenge1
M9k21/cakephp pull request #1
Opened 2020-09-06 13:03 UTC by M9k21

CakePHP課題
ミニオークションサイトの機能改善
 - 商品の詳細情報を投稿、表示する機能を追加
 - 商品の出品画像をアップロード、表示する機能を追加
 - オークション終了時刻のカウントダウンタイマーを追加

2020-09-08 11:30 UTC, n06Ar requested changes
レビューしました
何点かコメントをしているのでご確認をお願いします

-  auction.ctpの8行目、`$this->request->action`の`action`が`deprecated `なので気をつけてください
- AuctionControllerのbidで、終了時間超過した場合でも入札できてしまう可能性があります

2020-09-08 11:30 UTC, n06Ar commented on src/Template/auction/view.ctp
>                              <td><?= $bidrequest->created ?></td>
基本的にh()を使用するようにしてください

2020-09-08 11:30 UTC, n06Ar commented on src/Template/auction/view.ctp
> +                    var json_data = JSON.parse('<?= $json ?>');
`var`はスコープや変数名の重複による内容の書き換えなど不具合が発生しやすいので、`let`や`const`を使うようにして下さい

2020-09-08 11:30 UTC, n06Ar commented on src/Template/auction/add.ctp
>      echo '<p><strong>USER: ' . $authuser['username'] . '</strong></p>';
`$authuser['username']`は、h()をつけるようにしてください

2020-09-08 11:30 UTC, n06Ar commented on src/Controller/AuctionController.php
> +            $session->write('before_validate', $biditem);
バリデーションチェックのコード量が長いのでprivateなメソッドに処理を分離しても良いと思います

2020-09-08 11:30 UTC, n06Ar commented on src/Controller/AuctionController.php
>              if ($this->Biditems->save($biditem)) {
データを保存する時は、トランザクションを開始し例外処理ができる状態にしてください
データベースに保存時にエラーがあった時にロールバックをできるようにする目的があります

2020-09-08 11:30 UTC, n06Ar commented on src/Controller/AuctionController.php
> +            if ($biditem->errors()) {
errorsではなくgetErrorsを使うようにしてください
errorsは、`deprecated`な今後削除される機能です

2020-09-08 11:30 UTC, n06Ar commented on src/Template/auction/view.ctp
> +                                document.getElementById("countdown").innerHTML = "終了しました";
終了時は`《入札する！》`リンクを押せないようにしてください
画面で待機して終了してもController側で制御していないので入札できます

2020-09-20 06:46 UTC, M9k21 commented on src/Template/auction/view.ctp
>                              <td><?= $bidrequest->created ?></td>
修正リンク
071f760835f3e75e6f944c977aaf67879c4727ce

2020-09-20 06:46 UTC, M9k21 commented on src/Template/auction/view.ctp
> +                    var json_data = JSON.parse('<?= $json ?>');
修正リンク
5a7e478123552145d0f6bc1508bfd04385188250

2020-09-20 06:46 UTC, M9k21 commented on src/Template/auction/add.ctp
>      echo '<p><strong>USER: ' . $authuser['username'] . '</strong></p>';
修正リンク
071f760835f3e75e6f944c977aaf67879c4727ce

2020-09-20 06:46 UTC, M9k21 commented on src/Controller/AuctionController.php
> +            $session->write('before_validate', $biditem);
修正リンク
d2409732322efe89776838ec84a4316c556670e8

2020-09-20 06:48 UTC, M9k21 commented on src/Controller/AuctionController.php
>              if ($this->Biditems->save($biditem)) {
修正リンク
86fc4199db94b43a4d506f9d08d7d7bcfffbb39d

こちらについては現状エラーが出てしまっている状態ですがトランザクション自体は正常に動作していますので一度このまま提出させていただきます。
```
Undefined method 'begin'.
Undefined method 'commit'.
Undefined method 'rollback'.
```

もしこちらの記述内容で問題がないようでしたら他のデータ保存処理にもトランザクションを使うよう修正したいと考えています。

2020-09-20 06:48 UTC, M9k21 commented on src/Controller/AuctionController.php
> +            if ($biditem->errors()) {
修正リンク
50715348cd24b2c2f921ed1e355d1c1df730b6b2

2020-09-20 06:48 UTC, M9k21 commented on src/Template/auction/view.ctp
> +                                document.getElementById("countdown").innerHTML = "終了しました";
修正リンク
61c04005d871ed711e009092755ed6eaa0e8201d

2020-09-20 06:54 UTC, M9k21 commented
以下6点、修正いたしました。

 - 非推奨の記述を修正
 - AuctionControllerのbidで終了時間超過後に入札をできないように修正
 - viewで値を表示する際にh()を使うように修正
 - `view.ctp` scriptの`var`の記述を`let`または`const`を使った記述に修正
 - AuctionControllerのaddアクション内の画像のバリデーション処理を別のメソッドに分けるよう修正
 - 出品商品のデータベース保存にトランザクションを使用するよう修正

また、ご指摘いただいた以外の部分でAuctionControllerのaddとconfirmに分かれてしまっていた保存処理をconfirmにまとめるよう修正しました。（修正リンク 1808f3e78c500f1642ec76889f9861ca71bc8fc1）

その他1件、コメントに返信させていただきました。https://github.com/M9k21/cakephp/pull/1#discussion_r484835186

ご確認よろしくお願いいたします。

2020-09-22 10:17 UTC, n06Ar commented on src/Controller/AuctionController.php
>              if ($this->Biditems->save($biditem)) {
> もしこちらの記述内容で問題がないようでしたら他のデータ保存処理にもトランザクションを使うよう修正したいと考えています。

こちらですが、私の環境では、特にエラーはないので他の箇所でも同様な修正をお願いします。

2020-09-26 12:12 UTC, n06Ar commented on src/Controller/AuctionController.php
> +            $session->write('add_biditem', $biditem);
こちらEntityをセッションに格納していますが、`$biditem->toArray()`として連想配列を格納するようにしてください。
@M9k21 さんの環境では発生しませんでしたが、confirmメソッドでsessionから _add_biditem_ を取り出した際に、Biditemクラスであることがわからない問題が発生しました。
そのため、連想配列として格納しconfirmで取り出すときに（157行目）、`$biditem = $this->Biditems->newEntity($session->read('add_biditem'));`として取り出してください。

他の類似箇所でも上記と同じ対応をお願いしたいのもあります。

またこの対応をした場合は、confirmメソッドにてsessionから _add_item_ を取り出した時にfinishedなどの日付がFronzenTimeになっているので`i18nFormat()`を使い解決してください。

2020-09-26 12:14 UTC, n06Ar commented
> 以下6点、修正いたしました。
> 
> * 非推奨の記述を修正
> * AuctionControllerのbidで終了時間超過後に入札をできないように修正
> * viewで値を表示する際にh()を使うように修正
> * `view.ctp` scriptの`var`の記述を`let`または`const`を使った記述に修正
> * AuctionControllerのaddアクション内の画像のバリデーション処理を別のメソッドに分けるよう修正
> * 出品商品のデータベース保存にトランザクションを使用するよう修正
> 
> また、ご指摘いただいた以外の部分でAuctionControllerのaddとconfirmに分かれてしまっていた保存処理をconfirmにまとめるよう修正しました。（修正リンク [1808f3e](https://github.com/M9k21/cakephp/commit/1808f3e78c500f1642ec76889f9861ca71bc8fc1)）
> 
> その他1件、コメントに返信させていただきました。[#1 (comment)](https://github.com/M9k21/cakephp/pull/1#discussion_r484835186)
> 
> ご確認よろしくお願いいたします。

上記6点については、修正を確認できたのでこの点はOKです！

2020-09-27 02:33 UTC, M9k21 commented on src/Controller/AuctionController.php
>              if ($this->Biditems->save($biditem)) {
修正リンク
05fe5a9188dc9dfea86c22f3cb46fa026edacdd8

2020-09-27 02:33 UTC, M9k21 commented on src/Controller/AuctionController.php
> +            $session->write('add_biditem', $biditem);
修正リンク
59d3ed5992512032987c904c2197a6440ab266d6

2020-09-27 02:34 UTC, M9k21 commented
以下2点、修正いたしました。ご確認よろしくお願いいたします。

 - データベースの保存処理にトランザクションを実装
 - AuctionControllerのaddアクションからconfirmアクションへ値を渡す処理を修正

2020-09-27 06:58 UTC, n06Ar approved these changes
LGTMです！

今回は、比較的簡易な処理だったので特に言及しませんでしたが、MVCのModelとRoutingについて補足します。

## MVCのModelについて

（わかりづらい等ありましたら、質問タイム等で質問してください）
データベースにアクセスする下記の様なロジックは、基本的にModelの方に書くようにします。
（CakePHPでいうところの****Table.phpにメソッドを追加する形で実装します）
- Entityの作成と更新
- DBからのデータ取得

今回書いて気が付いたかと思いますが、Controllerのロジックが長くなっています。
これがさらに複雑になるとControllerの責務が重くなり、本来のViewからのリクエストを元にモデルを受け渡す役割以上のことをすることになります。
これは、実装の可読性や保守性に影響を与えることになります。

## Routing

基本的に、`config/route.php`にどのパスを入力したらどのControllerのMethodを呼ぶか定義することをお勧めします。
ここにルーティングの設定を書くと、URLからControllerのMethodを探すことができるだけではなく、POSTやGETのメソッドの指定や使用するパラメータと変数名の指定、カスタムルーティングなど便利なものがあるので使用することをお勧めします。
[ルーティング - 3.9](https://book.cakephp.org/3/ja/development/routing.html)

2020-09-29 05:20 UTC, merged